---

- name: Create netns interface config directory
  file:
    path: "/etc/default/netns-{{ netns_item.name }}/"
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Create netns overlay config directory
  file:
    path: "/etc/netns/{{ netns_item.name }}/"
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Configure netns overlay config files
  template:
    src: netns_overlay
    dest: "/etc/netns/{{ netns_item.name }}/{{ item.filename }}"
  with_items: "{{ netns_item.files | default([]) }}"

- name: Reset virtual interface count
  set_fact: veth_count=0

- name: Configure netns interfaces
  include_tasks: configure-netns-interface.yml
  with_items: "{{ netns_item.config }}"
