---

- name: Create netns interface config directory
  file:
    path: "/etc/default/netns-{{ netns_item.name }}/"
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Create netns overlay config directory
  file:
    path: "/etc/netns/{{ netns_item.name }}/"
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Configure netns overlay config files
  template:
    src: netns_overlay
    dest: "/etc/netns/{{ netns_item.name }}/{{ item.filename }}"
  loop: "{{ netns_item.files | default([]) }}"
  loop_control:
    label: "{{ item.filename }}"

- name: Reset virtual interface count
  set_fact:
    veth_count: 0

- name: Configure netns interfaces
  include_tasks:
    file: configure-netns-interface.yml
  loop: "{{ netns_item.config }}"
  loop_control:
    label: "{{ item.interface | default(item.type) }}"
